name: check-community-approval
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
permissions: read-all

jobs:
  check-community-approval:
    name: check-community-approval
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/check-community-approval.yaml@v2.0.0
    secrets: inherit
