name: check-community-approval-label
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
permissions:
  contents: read

jobs:
  check-community-approval-label:
    name: check-community-approval-label
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/check-pr-label.yaml@v2
    with:
      label: "community-approved"
