name: OSSF Scorecard
on:
  schedule:
    - cron: '0 5 * * 1' # Every Sunday at 10pm MST (5:00 UTC)
  push:
    branches: [ "main" ]

jobs:
  analysis:
    permissions:
      security-events: write
      id-token: write
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/ossf-scorecard.yaml@convert_reusable_workflows
    secrets: inherit
