name: Semver Release
on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/semver-release.yaml@convert_reusable_workflows
    secrets: inherit
