name: validate-pr-title
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
permissions: read-all

jobs:
  validate-pr-title:
    name: validate-pr-title
    permissions:
      pull-requests: read
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/validate-pr-title.yaml@v2.0.0
    secrets: inherit
