name: "Validate PR Title"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  validate_pr_title:
    permissions:
      pull-requests: read
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/validate-pr-title.yaml@convert_reusable_workflows
    secrets: inherit
