name: validate-pr-title
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
permissions: read-all

jobs:
  validate-pr-title:
    name: validate-pr-title
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/check-conventional-commit-pr-title.yaml@v2
